apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
    apps: webapps
  ports:
    - name: http
      port: 80
      nodePort: 32000
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    apps: webapps
spec:
  containers:
  - name: pod1
    image: nginx
    ports:
      - containerPort: 80
# Ignore this section (not mandatory)
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "5000m"

