apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    app: nginx
spec:
  containers: 
  - name: cont1
    image: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "5000m"
