apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      namespace: name of the space        # Ignore this line
      labels:
        app: hello 
    spec:
      containers:
        - name: hello     # any name of the container
          image: httpd
          
          
          port:
          - containerPort: 80
  
  
  
  # Ignore this section as of now (not namdatory)
      resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "5000m"

