- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Going to install webserver
      yum:
         name: httpd
         state: present
    - name: Going to start the webserver
      service:
         name: httpd
         state: started 
    - name: Going to push code into webserver path-deploy
      copy: 
         src: ./index.html
         dest: /var/www/html/index.html
         mode: '0777' 