- hosts: all
  remote_user: ansadmin
  become: yes
  tasks:
    - name: Update slaves servers
      yum:
        name: "*"
        state: latest
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: install Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /opt/tomcat
        mode: '777'
    - name: Untar Tomcat 
      unarchive:
        src: /opt/tomcat/apache-tomcat-9.0.65.tar.gz
        dest: /opt
        remote_src: yes
        mode: '777'
    - name: Start tomcat 
      shell: nohup /opt/tomcat/apache-tomcat-9.0.65/bin/startup.sh &
    - name: Copy war file
      copy:
        src: /opt/naba/webapp/target/webapp.war
        dest: /opt/tomcat/apache-tomcat-9.0.65/webapps
