- hosts: tom
  remote_user: ec2-user
  become: yes
  vars:
      tomcat_port: 6060
  tasks:
    - name: Update slaves servers
      yum:
        name: "*"
        state: latest
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Install Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /opt
        mode: '777'
    - name: untar tomcat 
      unarchive:
        src: /opt/apache-tomcat-9.0.65.tar.gz
        dest: /opt
        remote_src: yes
        mode: '777'
    - name: Start tomcat 
      shell: nohup /opt/apache-tomcat-9.0.65/bin/startup.sh &
    - name: Change port number of tomcat
      template:
        src: ./server.xml.j2
        dest: /opt/apache-tomcat-9.0.65/conf/server.xml
        mode: '777'
    - name: Shut-down Tomcat
      shell: nohup /opt/apache-tomcat-9.0.65/bin/shutdown.sh &
    - name: Start tomcat 
      shell: nohup /opt/apache-tomcat-9.0.65/bin/startup.sh &
    - name: Going to Deploy sample.war file 
      copy:
        src: ./sample.war
        dest: /opt/apache-tomcat-9.0.65/webapps/sample.war