# To create a Daemon Set
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-example             # Unique key of the DaemonSet instance
spec:
  selector:
    matchLabels:
      app: daemonset-example
  template:
    metadata:
      labels:
        app: daemonset-example
    spec:
      containers:
      - name: daemonset-example      # This container is run once on each Node in the cluster (container name)
        image: ubuntu:trusty


---


apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mynode-exporter
  labels:
    app: mynode-exporter
spec:
  selector:
    matchLabels:
      app: mynode-exporter
  template:
    metadata:
      labels:
        app: mynode-exporter
    spec:
       containers:
          - name: mynode-exporter
            image: prom/node-exporter:v0.18.1
            ports:
              - containerPort: 9100
                hostPort: 9100
                protocol: TCP
